# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.18'

      - name: Install dependencies
        run: go mod download

      - name: Run Tests
        run: go test ./... -v

      - name: Run Linting
        uses: golangci/golangci-lint-action@v3
        with:
          version: 'latest'

      - name: Code Quality Check - Go Report Card
        run: |
          curl -s https://goreportcard.com/checks/github.com/your-username/json-analyzer-cli | grep -i "A\|B\|C\|D\|E"
